[package]
name = "token-receiver"
version = "0.0.1"
authors = ["Zane <zane@ships.gold>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0" 
multi-token-standard = { path = "../../../multi_token" }