  
[package]
name = "semi-fungible-token"
version = "0.0.1"
authors = ["Ships Gold zane@ships.gold"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0" 
semi-fungible-token-standard = { path = "../../../semi_fungible_token" }